# Generated by Django 4.1.7 on 2023-02-28 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_postmodel_mark_of_translate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolModelBro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limited_integer_field', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='mark_of_translate',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
