# Generated by Django 4.1.7 on 2023-02-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_delete_coolmodelbro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='mark_of_translate',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=2),
        ),
    ]
