# Generated by Django 4.1.7 on 2023-03-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_alter_postmodel_mark_of_translate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='mark_of_translate',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('No mark', 'N')], default='No mark', max_length=7),
        ),
    ]
