# Generated by Django 4.1.7 on 2023-03-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0007_alter_postmodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='author',
            new_name='user',
        ),
    ]
