# Generated by Django 4.1.7 on 2023-03-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0010_dictionarymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionarymodel',
            old_name='author',
            new_name='user',
        ),
    ]
